### ISSUE TITLE
Give Credit

### ISSUE THREAD

**Issue by shubhamhackz** [ankithans/Covid-19-Tracker#10]
Nice to see you guys are using flutter to make such good apps. Just wanted to say at least give credits to the repo https://github.com/shubhamhackz/aarogya_seva from where you used Chat functionality in your app. It took lot of time to develop Aarogya Seva and as so guys are also developers you can understand. Please give a link of our repo in your readme.

**Comment by ankithans** [comment]
Hello @shubhamhackz  I was unaware of using chat functionality from aarogya_seva application. @Kurubaran-18  has recently contributed to this repo for the chat functionality. If this is the case I definitly want to give credits to your repo.
Thanks @shubhamhackz  for informing.

**Comment by shubhamhackz** [comment]
Please do so.
