### ISSUE TITLE
Remove "state unassigned" coming from api in statewise List

### ISSUE THREAD

**Issue by ankithans** [ankithans/Covid-19-Tracker#13]
**Describe the bug**
Remove "state unassigned" coming from api in statewise List.

**Screenshots**
![image](https://user-images.githubusercontent.com/50692897/94734378-c7f2a100-0386-11eb-868a-62654c5793ad.png)

**Comment by AgungPrabowo** [comment]
@ankithans only text or a section?

**Comment by Abhijeet-sonkar** [comment]
Can I work on this issue?

**Comment by ankithans** [comment]
@AgungPrabowo go ahead!

**Comment by ankithans** [comment]
@AgungPrabowo we need to remove full card!

**Comment by ankithans** [comment]
@Abhijeet-sonkar go ahead! should I assign this issue to you?

**Comment by Abhijeet-sonkar** [comment]
Yes please :)

**Comment by ankithans** [comment]
done @Abhijeet-sonkar !

**Comment by ankithans** [comment]
@Abhijeet-sonkar do give it a star too 😅. We are close to 30.

**Comment by ankithans** [comment]
Thanks @Abhijeet-sonkar for your contribution!
