### ISSUE TITLE
Decrease line space between confirmed Active Recovered Decreased cases in states page

### ISSUE THREAD

**Issue by ankithans** [ankithans/Covid-19-Tracker#14]
**Describe the bug**
Decrease line space between confirmed Active Recovered Decreased cases in states page

**Screenshots**
![image](https://user-images.githubusercontent.com/50692897/94734892-83b3d080-0387-11eb-987a-5eae539bfdec.png)

**Comment by Abhijeet-sonkar** [comment]
Can I work on this issue?

**Comment by ankithans** [comment]
This issue has been solved by @USHIERU !
