### ISSUE TITLE
Remove Back button from Health self assessment

### ISSUE THREAD

**Issue by ankithans** [ankithans/Covid-19-Tracker#15]
**Describe the bug**
Remove Back button from Health self assessment.

**Screenshots**
![image](https://user-images.githubusercontent.com/50692897/94735293-25d3b880-0388-11eb-8c2d-104171693983.png)

**Comment by stijnvdkolk** [comment]
Can I fix this tomorrow?

**Comment by ankithans** [comment]
sure @Kolkies ! 
Also do star the repo 😅

**Comment by AgungPrabowo** [comment]
Hi @ankithans , can you assign me this issue?

**Comment by jatinjain001** [comment]
I want to work on this issue If it is available
