### ISSUE TITLE
Some Big Numbers are not seperated with commas

### ISSUE THREAD

**Issue by ankithans** [ankithans/Covid-19-Tracker#18]
**Describe the bug**
Some Big Numbers are not seperated with commas.

**Expected behavior**
Big numbers should also be seperated by commas!

**Screenshots**
![image](https://user-images.githubusercontent.com/50692897/94770194-9eab3280-03d1-11eb-9052-d194abc7e3da.png)
![image](https://user-images.githubusercontent.com/50692897/94770406-31e46800-03d2-11eb-86eb-5da51b48b915.png)

**Comment by shraddhahinge** [comment]
Instead of separating by commas, I can make the big number convert into units like e.g 1000 = 1k. If this is applicable let me know, I would love to make changes in big numbers😉👩‍💻

**Comment by jatinjain001** [comment]
I want to work on this issue ..

**Comment by ankithans** [comment]
sure @shraddhahinge go ahead! That will be better.

**Comment by jatinjain001** [comment]
I also can do it .If it would be available then please assign me further

**Comment by ankithans** [comment]
@shraddhahinge this will cause issues like spacing in between 
It will cause empty space in between.

**Comment by ankithans** [comment]
> I also can do it .If it would be available then please assign me further

go ahead @jatinjain001  🎉 its now assigned to you

**Comment by ankithans** [comment]
And do star this repo if you liked 😅

**Comment by jatinjain001** [comment]
thank you
Bro I wanna know that maximum number of digits we are displaying , Can you please tell me

**Comment by ankithans** [comment]
@jatinjain001  data is comming from api. And it will increase day by day.

**Comment by Sirsho29** [comment]
Is the issue resolved?

**Comment by ankithans** [comment]
Not yet!! @Sirsho29

**Comment by Sirsho29** [comment]
Okay please assign it to me. I can solve the issue

**Comment by ankithans** [comment]
sure @Sirsho29 !! go ahead.

**Comment by ankithans** [comment]
please give it a star too!!

**Comment by Sirsho29** [comment]
I have resolved the issue. Its working now. Please check and accept the PR.

**Comment by ankithans** [comment]
Thank you for contributing @Sirsho29 !

**Comment by Sirsho29** [comment]
Welcome. You have a made a very nice app. Very well written codes. Congrats on that.
