### ISSUE TITLE
Indian States Name was overflow.

### ISSUE THREAD

**Issue by tsvillain** [ankithans/Covid-19-Tracker#2]
In States page the Dadra and Nagar Haveli State name is overflowed or second line is not visible.

**Comment by tsvillain** [comment]
@ankithans can you assign this to me, I will love to contribute to this repo.

**Comment by tsvillain** [comment]
@ankithans assign this issue to me I will handle it.

**Comment by ankithans** [comment]
Done @tsvillain !

**Comment by tsvillain** [comment]
> 
> 
> Done @tsvillain !

Thanks I had create a PR regarting same.
