### ISSUE TITLE
The application will crash for new flutter_bloc :^6.0.6

### ISSUE THREAD

**Issue by ashwinikumar01** [ankithans/Covid-19-Tracker#22]
****Describe the bug**
**I HAVE FIXED THE OLDER BLOC WITH NEWER AND MODIFIED BLOC PATTERN AS THE APP WAS CRASHING WITH OLDER BLOC AND I JUST NEED TO PULL THE REQUEST AND SUBMIT .****

I HAVED FIXED IT WITH NEWER BLOC PATTERN AND WORKING GOOD IN DEVICES.

**Comment by ankithans** [comment]
@ashwinikumar01 we cannot shift to newer version of flutter bloc.
As there will be some breaking changes in newer versions on ```flutter_bloc``` package.

**Comment by ashwinikumar01** [comment]
Yeah @ankithans  i have updated with newer version

**Comment by ashwinikumar01** [comment]
@ankithans the app is no longer crashing

**Comment by ashwinikumar01** [comment]
I updated the full app

**Comment by ankithans** [comment]
we cannot take the risk of any kind of vulnerability introduced due to versions of packages. That's why versions of packages are introduced so that no issues will be there while using prevous versions also.

**Comment by ashwinikumar01** [comment]
Hey, @ankithans  I have created a pull request, have a look to it. This is with newer bloc pattern.
![1](https://user-images.githubusercontent.com/69667369/95420166-ab430400-0958-11eb-826c-f1f8a2f92e6e.jpeg)
![2](https://user-images.githubusercontent.com/69667369/95420177-aed68b00-0958-11eb-98e3-e07382650d77.jpeg)
![3](https://user-images.githubusercontent.com/69667369/95420181-b138e500-0958-11eb-9dab-25ec8726d95f.jpeg)
