### ISSUE TITLE
Numbers are not properly separated in Indian states card

### ISSUE THREAD

**Issue by ashwinikumar01** [ankithans/Covid-19-Tracker#25]
**Describe the bug**
Numbers are not properly separated in Indian states card

![Annotation 2020-10-08 141343](https://user-images.githubusercontent.com/69667369/95435710-89557b80-0970-11eb-987a-08118a806f9f.jpg)

**Comment by ashwinikumar01** [comment]
I have fixed this issue just needed to create a pull request.

**Comment by ankithans** [comment]
ok @ashwinikumar01 you are assigned to this issue!
